# Generated by Django 2.2.28 on 2024-12-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seon', '0002_auto_20241226_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='codter',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código del Tercero'),
        ),
    ]
