# Generated by Django 2.2.28 on 2024-12-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seon', '0003_auto_20241227_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tercero',
            options={'managed': False, 'ordering': ['nomter'], 'verbose_name': 'Tercero', 'verbose_name_plural': 'Terceros'},
        ),
    ]
